FROM python:3.11-slim
WORKDIR /app
COPY train_model.py /app/train_model.py
COPY data_preprocessing.py /app/data_preprocessing.py
RUN pip install --no-cache-dir scikit-learn joblib pandas
CMD ["python", "train_model.py"]
